import { Question } from "./types";

const opts = (...options: [string, string, string, string]) => options;

const baseQuestions: Question[] = [
  {
    id: "q1",
    category: "Tecnología",
    difficulty: 1,
    text: "¿Qué lenguaje se ejecuta directamente en la mayoría de navegadores?",
    options: opts("Python", "JavaScript", "Rust", "Go"),
    correctIndex: 1,
    maxTime: 30,
    points: 100,
  },
  {
    id: "q2",
    category: "Criptografía",
    difficulty: 1,
    text: "¿Cuál es la unidad mínima de ETH?",
    options: opts("Gwei", "Finney", "Wei", "Szabo"),
    correctIndex: 2,
    maxTime: 35,
    points: 100,
  },
  {
    id: "q3",
    category: "World ID",
    difficulty: 2,
    text: "¿Qué comando de MiniKit valida persona única?",
    options: opts("verify", "pay", "share", "walletAuth"),
    correctIndex: 0,
    maxTime: 30,
    points: 200,
  },
  {
    id: "q4",
    category: "Desarrollo",
    difficulty: 2,
    text: "¿Qué variable de entorno define el ID de la mini app?",
    options: opts("NEXT_PUBLIC_APP_ID", "APP_SECRET", "CHAIN_ID", "NEXT_API_KEY"),
    correctIndex: 0,
    maxTime: 25,
    points: 250,
  },
  {
    id: "q5",
    category: "Mecánicas",
    difficulty: 2,
    text: "¿Cuántas preguntas tiene el modo clásico 50x15?",
    options: opts("10", "12", "15", "20"),
    correctIndex: 2,
    maxTime: 20,
    points: 250,
  },
  {
    id: "q6",
    category: "MiniKit",
    difficulty: 3,
    text: "¿Qué comando MiniKit vibra el dispositivo?",
    options: opts("sendHapticFeedback", "pay", "verify", "walletAuth"),
    correctIndex: 0,
    maxTime: 25,
    points: 300,
  },
  {
    id: "q7",
    category: "MiniKit",
    difficulty: 3,
    text: "¿Qué comando se usa para pagos on-chain?",
    options: opts("pay", "verify", "request", "impact"),
    correctIndex: 0,
    maxTime: 25,
    points: 350,
  },
  {
    id: "q8",
    category: "Trivia",
    difficulty: 3,
    text: "¿Qué comodín elimina dos opciones incorrectas?",
    options: opts("Público", "50/50", "Cambio", "Tiempo extra"),
    correctIndex: 1,
    maxTime: 20,
    points: 400,
  },
  {
    id: "q9",
    category: "World Chain",
    difficulty: 3,
    text: "¿Qué red usa World Chain en testnet actualmente?",
    options: opts("Sepolia", "Mainnet", "Polygon", "Base"),
    correctIndex: 0,
    maxTime: 25,
    points: 400,
  },
  {
    id: "q10",
    category: "World ID",
    difficulty: 4,
    text: "¿Qué acción se recomienda al abrir la app por primera vez?",
    options: opts("Pagar", "Compartir", "Verify", "Cerrar"),
    correctIndex: 2,
    maxTime: 25,
    points: 500,
  },
  {
    id: "q11",
    category: "Tokenomics",
    difficulty: 4,
    text: "¿Qué token es el buy-in principal sugerido para torneos?",
    options: opts("USDT", "WLD", "ETH", "DAI"),
    correctIndex: 1,
    maxTime: 20,
    points: 550,
  },
  {
    id: "q12",
    category: "App Router",
    difficulty: 4,
    text: "¿Qué enrutador usa este proyecto de Next.js?",
    options: opts("Pages Router", "App Router", "Express", "Remix"),
    correctIndex: 1,
    maxTime: 20,
    points: 600,
  },
  {
    id: "q13",
    category: "MiniKit",
    difficulty: 4,
    text: "¿Qué comando se usa para registrar un resultado on-chain?",
    options: opts("sendTransaction", "pay", "verify", "haptic"),
    correctIndex: 0,
    maxTime: 25,
    points: 650,
  },
  {
    id: "q14",
    category: "Arquitectura",
    difficulty: 4,
    text: "¿Dónde se recomienda guardar la sesión localmente?",
    options: opts("Cookies", "IndexedDB/localStorage", "SessionStorage", "Redis"),
    correctIndex: 1,
    maxTime: 25,
    points: 700,
  },
  {
    id: "q15",
    category: "Pagos",
    difficulty: 5,
    text: "¿Qué endpoint de ejemplo inicia un pago en este repo?",
    options: opts("/api/initiate-payment", "/api/notify", "/api/profile", "/api/questions"),
    correctIndex: 0,
    maxTime: 20,
    points: 800,
  },
  {
    id: "q16",
    category: "Haptics",
    difficulty: 5,
    text: "¿Qué estilo se usa para indicar error en feedback háptico?",
    options: opts("light", "success", "error", "warning"),
    correctIndex: 2,
    maxTime: 15,
    points: 850,
  },
  {
    id: "q17",
    category: "Torneos",
    difficulty: 5,
    text: "¿Qué dato se pasa como reference al comando pay en torneos?",
    options: opts("userId", "tournamentId", "score", "wallet"),
    correctIndex: 1,
    maxTime: 20,
    points: 900,
  },
  {
    id: "q18",
    category: "Torneos",
    difficulty: 5,
    text: "¿Qué acción dispara una notificación al ganar?",
    options: opts("sendNotification", "sendHapticFeedback", "verify", "askAudience"),
    correctIndex: 0,
    maxTime: 20,
    points: 950,
  },
];

export const questions: Question[] = [...baseQuestions].sort((a, b) => a.difficulty - b.difficulty);

export function getAlternateQuestion(current: Question, usedIds: Set<string>) {
  return questions.find(
    (candidate) => candidate.difficulty === current.difficulty && !usedIds.has(candidate.id),
  );
}
